name: Teste Auth Service

on: 
    
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    
jobs:
    test-auth-service:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout de código
              uses: actions/checkout@v4

            - name: Configurar Python 3.12.4
              uses: actions/setup-node@v4
              with:
                python-version: '3.12.4'

            - name: Install dependencies
              working-directory: ./burguer-app/auth-service
              run: |
                pip install -r requirements.txt

            - name: Rodar testes

              run: |
               mkdir -p reports
               pytest -v  --cov=models --cov=services --cov=config --cov=controllers --html=reports/report.html --self-contained-html
               radon cc ./burguer-app/auth-service/models/user_model.py
            
            - name: Upload HTML Report
              uses: actions/upload-artifact@v4
              if: always() # Garante que o relatório seja salvo mesmo se algum teste falhar
              with:
                name: pytest-html-report
                path: reports/report.html
                retention-days: 7


            
              

            